# Generated by Django 4.2.8 on 2024-01-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='audio_num',
            field=models.BigIntegerField(default=0, verbose_name='音频数量'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='check_num',
            field=models.BigIntegerField(default=0, verbose_name='核验音频数量'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cut_num',
            field=models.BigIntegerField(default=0, verbose_name='切分音频数量'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='emo_down',
            field=models.BigIntegerField(default=0, verbose_name='客服负向情感'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='emo_norm',
            field=models.BigIntegerField(default=0, verbose_name='客服中性情感'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='emo_up',
            field=models.BigIntegerField(default=0, verbose_name='客服正向情感'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_emo_down',
            field=models.BigIntegerField(default=0, verbose_name='用户负向情感'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_emo_norm',
            field=models.BigIntegerField(default=0, verbose_name='用户中性情感'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_emo_up',
            field=models.BigIntegerField(default=0, verbose_name='用户正向情感'),
        ),
    ]
