# Generated by Django 4.2.8 on 2024-01-17 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recognition_time', models.DateTimeField(auto_now_add=True, verbose_name='识别时间')),
                ('frame_num', models.IntegerField(verbose_name='分割帧数')),
                ('left_emotions', models.JSONField(verbose_name='左声道情感')),
                ('right_emotions', models.JSONField(verbose_name='右声道情感')),
                ('audio_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emotion', to='audio.audio', verbose_name='音频')),
            ],
        ),
    ]
