# Generated by Django 4.2.8 on 2024-01-15 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('upload_events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orig_file_path', models.CharField(max_length=256, unique=True, verbose_name='原始音频文件路径')),
                ('left_file_path', models.CharField(max_length=256, unique=True, verbose_name='音频左声道文件路径')),
                ('right_file_path', models.CharField(max_length=256, unique=True, verbose_name='音频右声道文件路径')),
                ('upload_event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio', to='upload_events.uploadevent', verbose_name='上传事件')),
            ],
        ),
    ]
