# Generated by Django 4.2.8 on 2024-01-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='是否已审核'),
        ),
    ]
