# Generated by Django 4.2.8 on 2024-02-01 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audio', '0002_audio_checked'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cut_audio_path', models.CharField(max_length=256, verbose_name='被剪辑音频文件路径')),
                ('start_time', models.FloatField(verbose_name='片段开始时间')),
                ('end_time', models.FloatField(verbose_name='片段结束时间')),
                ('part_path', models.CharField(max_length=256, null=True, verbose_name='音频片段存储路径')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cut_user', to=settings.AUTH_USER_MODEL, verbose_name='剪辑片段用户')),
            ],
        ),
    ]
