# Generated by Django 4.2.8 on 2024-04-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SERModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='模型名称')),
                ('path', models.FileField(upload_to='ser_models', verbose_name='语音情感识别模型文件')),
            ],
        ),
    ]
