# Generated by Django 4.2.8 on 2024-01-03 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('file', models.FileField(upload_to='upload_files/%Y/%m/%d', verbose_name='上传文件')),
                ('cs_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cs_events', to=settings.AUTH_USER_MODEL, verbose_name='客服用户')),
            ],
        ),
    ]
